-- http://www.generatedata.com/

INSERT IGNORE INTO `user` (`email`,`password`) VALUES ("test@user.com","QZB90HIU3VJ");
INSERT IGNORE INTO `user` (`email`,`password`) VALUES ("orci@Maecenas.co.uk","QPZ58ATU7ZD"),("eu@quis.co.uk","XPH96GYV7TQ"),("velit@velmauris.org","DVB42DUT9UH"),("erat.Vivamus@ametconsectetuer.edu","BWC72NTZ5RR"),("quis.urna@vehicula.co.uk","MAA64ACA4DJ"),("ac.mi@Phasellusnulla.edu","IRQ41DDM4BX"),("non.sollicitudin.a@ipsumdolor.com","TOF07UZR1JC"),("ipsum.porta.elit@commodo.net","MPT18EAL5TG"),("aliquet.nec@sitametrisus.org","XTI24YZR6QB"),("in@Maurisquis.co.uk","EGX43TGK9KZ"),("Mauris@odioEtiamligula.co.uk","FRL15RVT3FM"),("augue@mollis.ca","LWE49YWR1WE"),("Etiam.imperdiet@nonluctussit.ca","WXA09LWT8MU"),("odio.vel@velvenenatisvel.ca","CJV99KAZ0FT"),("Suspendisse.eleifend.Cras@antedictumcursus.ca","IYN24VZK4KX"),("magna@lacus.com","JCG42VYW6HC"),("ac@sitametmassa.org","GPU19PLP5WI"),("est@dolorsit.edu","YGQ96EOB0ME"),("odio.tristique@nullaat.net","KOC35GEE8JM"),("enim@sollicitudinorci.edu","NTU20UYJ3NX"),("Nam@massaQuisqueporttitor.net","AQD47POV7NO"),("Mauris.vel@ipsumSuspendisse.ca","AUK42ATT4II"),("Nam@tristiquealiquetPhasellus.net","JOB71EVJ5PX"),("Mauris.non.dui@lectusantedictum.ca","KAB45WLJ2BR"),("tempus.risus.Donec@tortornibh.edu","GNU27YWG8XF"),("vestibulum.massa@aauctor.co.uk","PQU48WGG6BN"),("libero.nec.ligula@ipsumPhasellus.ca","XAV53EXP0CX"),("eu@Uttinciduntorci.co.uk","IHN30WWQ0BJ"),("pede@infaucibus.org","QZB90HIU3VJ"),("dolor@faucibusidlibero.org","MLK75YSX1CB");
INSERT IGNORE INTO `user` (`email`,`password`) VALUES ("Donec.consectetuer@Maurisquis.co.uk","OWL71JDE4NF"),("Nulla.semper@massa.co.uk","TXR78LKS5AC"),("arcu.eu@nuncullamcorpereu.edu","MNY35LKU5OF"),("purus@ornare.co.uk","CQW87CLW2NA"),("Suspendisse@euaccumsansed.ca","YCX78XMN3JM"),("nonummy.ut@Quisque.edu","KNB85BGU0PV"),("fames@lorem.net","ZSC95MRR1WX"),("pede.ultrices.a@parturientmontesnascetur.co.uk","BNI14WTO5RB"),("Curabitur@Fusce.edu","PKF55DHH0CJ"),("sagittis@orci.ca","YOJ60ONK1SN"),("dui.nec@Nullaaliquet.org","ROV63HNS2TL"),("vitae.posuere.at@auctornonfeugiat.edu","HOD23IEC8UL"),("egestas.Aliquam.nec@dolornonummyac.org","NFY48RKQ9KL"),("Cras.convallis@est.net","YIG23DSS5ZV"),("sagittis.placerat@vel.edu","HFY93GTC3WP"),("mi@velitinaliquet.net","DRK95LHJ5WU"),("Suspendisse.sagittis.Nullam@ultriciesdignissimlacus.com","VKY19TXO8KV"),("massa.Integer@etnetus.edu","GQE22KXB4JA"),("dictum@Etiam.co.uk","ZNB10ULL9LY"),("et.libero.Proin@vellectus.edu","FQD54YDS4CT"),("non@duiCum.net","SAC71LEB3HP"),("mauris.sit@luctus.co.uk","YDL06YPJ5HP"),("Ut@Aliquamtincidunt.edu","RRN65OYS7UR"),("Quisque.imperdiet@aliquamarcu.edu","SXG98BEZ4DI"),("elit.dictum@ac.ca","UFT26IFV8LN"),("cursus.diam.at@lectusjustoeu.edu","RUO51PZU5UP"),("egestas.Fusce.aliquet@tinciduntcongue.edu","PHS85ESA7YI"),("vulputate.velit@sedsapien.com","WIS86ZOH5HU"),("turpis.egestas@nonsollicitudina.org","OKB47ALO6QF"),("nulla.Cras.eu@elitNulla.org","VBJ45IDQ2KI");
INSERT IGNORE INTO `user` (`email`,`password`) VALUES ("dapibus.rutrum.justo@Duisgravida.co.uk","TTR92HAA5MR"),("non.vestibulum.nec@vel.ca","YCS25OIF9JD"),("dapibus.rutrum@magnisdisparturient.org","ECE68AWJ3CD"),("lectus.rutrum.urna@lectus.net","TPN20EEC7UV"),("In.mi.pede@auctorodio.com","QBM41XLQ0RM"),("sit@quis.edu","AZC23CXX2OO"),("ante.Nunc@Maurisquisturpis.org","FZJ47MDR6KG"),("mauris.elit.dictum@estarcuac.org","COP28HRF7GW"),("lorem.fringilla.ornare@metusIn.ca","ZXD96XTG1MY"),("augue@acfacilisisfacilisis.com","UHH64CCD9YB"),("neque.tellus@ipsumdolor.co.uk","LBJ64DQF7GW"),("nibh.dolor@Nam.com","NQH80BAA2CB"),("enim.sit@estmauris.com","FQR18YZA0BT"),("non.vestibulum.nec@miloremvehicula.co.uk","GVP77CKV9XR"),("arcu.et@NuncmaurisMorbi.co.uk","UNX91QGG7FK"),("eleifend@nuncnullavulputate.com","UFC06XCP5SO"),("enim.Etiam.imperdiet@acfermentumvel.net","SNC24WSI5MX"),("mauris.sit.amet@purus.com","GZL87LDE5XY"),("ut.nulla.Cras@Vivamussitamet.net","XTL31CTC0AU"),("Cras.sed@nonummy.org","VIQ85NOQ1AM"),("enim@purusMaecenaslibero.edu","QFM83IAB9EA"),("enim.Curabitur.massa@sed.net","GSO10ENE1DD"),("sollicitudin@semeget.com","NYS54OSZ5ZC"),("Duis@necmetusfacilisis.com","ZYN23RYM7JP"),("sit.amet.nulla@gravidasagittis.ca","WBP92PZK1MN"),("rutrum.Fusce@placerat.co.uk","CJP59BLH2YT"),("amet.ornare.lectus@etarcuimperdiet.edu","ATL87VOR9JQ"),("arcu@Maurisblanditenim.ca","SGA48XXE0PQ"),("penatibus.et.magnis@lacus.com","UIZ46VCV0LO"),("leo.Cras@MaurismagnaDuis.org","NWW93XDX6SE");

INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("dolor dapibus",3148),("eu tempor",5429),("vitae, posuere",8703),("molestie arcu.",9579),("aliquet. Phasellus",5588),("congue a,",2288),("Nam consequat",887),("Morbi sit",2216),("risus odio,",2495),("risus. Donec",7161);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("purus, in",2460),("magna. Phasellus",3306),("nec, diam.",1652),("gravida. Praesent",7230),("nascetur ridiculus",7312),("sit amet,",4597),("ac, fermentum",8916),("et magnis",4512),("dapibus id,",9663),("quam a",4506);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("massa. Vestibulum",7230),("tincidunt, neque",1937),("parturient montes,",5166),("tempus, lorem",1011),("ultrices. Vivamus",782),("cursus purus.",8020),("ultrices iaculis",4849),("molestie dapibus",9250),("Morbi vehicula.",2894),("Duis ac",6642);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("facilisi. Sed",6655),("blandit congue.",7193),("lacus. Mauris",4317),("a mi",6191),("Proin dolor.",6232),("non, hendrerit",9273),("Aenean euismod",9150),("urna. Nullam",275),("ut cursus",1739),("ullamcorper magna.",8075);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("dictum. Proin",8435),("dictum augue",4046),("pretium aliquet,",5818),("dolor. Fusce",2627),("mollis nec,",1121),("Ut semper",7608),("fermentum vel,",9292),("neque sed",5145),("lobortis augue",4046),("ipsum sodales",3094);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("mi lorem,",2488),("nunc nulla",1710),("iaculis aliquet",4080),("montes, nascetur",7363),("nunc id",1848),("et, magna.",2151),("tristique pellentesque,",607),("ac turpis",289),("at, iaculis",4524),("elit. Etiam",2518);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("eu dui.",2844),("non quam.",9745),("hendrerit id,",5739),("facilisis. Suspendisse",4583),("lacus. Cras",1489),("nunc sed",8253),("arcu et",3009),("nec quam.",6231),("mauris blandit",5285),("nisl. Quisque",2013);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("leo elementum",7928),("metus. Aenean",2676),("Vivamus non",8776),("Curabitur consequat,",2358),("aliquet vel,",2102),("varius ultrices,",1609),("arcu. Vestibulum",8477),("Suspendisse ac",4136),("Quisque tincidunt",6271),("Pellentesque ultricies",2659);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("lobortis augue",6441),("non, bibendum",5054),("dolor. Fusce",7405),("Duis gravida.",867),("rutrum urna,",2155),("quam quis",4394),("facilisis non,",3096),("mauris ipsum",363),("Aliquam ornare,",8172),("Duis elementum,",8329);
INSERT IGNORE INTO `product` (`name`,`price`) VALUES ("Quisque tincidunt",9021),("vestibulum nec,",4881),("a, enim.",1674),("ante dictum",3037),("tincidunt, neque",4227),("Pellentesque tincidunt",4128),("odio. Phasellus",8086),("mollis. Integer",2415),("rhoncus. Donec",5489),("nec, leo.",9409);

